version: '3.6'  

    
services:  
  parser:
    build: 
      context: ./
    #command: bash -c "make"
    volumes:
      - data-volume:/parser
    depends_on:   
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    restart: always
  redis:
    image: redis:3.2-alpine

  bot:
    build: 
      context: ./docker/bot
    depends_on: 
      - redis
    volumes: 
       - data-volume:/bot
volumes:
 data-volume: 
    external: true
   