version: '3.2'  

    
services:  
  parser:
    image: parser
    #volumes:
     # - data-volume:var/lib/usr/src/my_app_directory                  
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    restart: always
  redis:
    image: redis:3.2-alpine

  #bot:
   # image: bot
    #links: 
     #   - parser
    #volumes: 
     #   - data-volume:var/lib/usr/src/my_app_directory         
#volumes:
 #data-volume:
   