version: '3.6'  
volumes:
    staticfiles: {}
services:  
  parser:
    image: parser
    volumes:
             - staticfiles:/projects                   
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    restart: always
  redis:
    image: redis:3.2-alpine

  #bot:
    #image: bot
    #links: 
     #   - parser
    #volumes:
     #   - staticfiles:/projects