version: '3.6'  

    
services:  
  parser:
    #image: parser
    build: 
      context: ./
    command: bash -c "make"
      #working_dir: /parser
    volumes:
      - data-volume:/parser
    depends_on:   
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    restart: always
  redis:
    image: redis:3.2-alpine

  bot:
    #image: bot
    build: 
      context: ./docker/bot
    #working_dir: /bot
    depends_on: 
      - redis

    #links: 
    #   - parser
    volumes: 
       - data-volume:/bot
volumes:
 data-volume: 
    external: true
   